isMaximizeObj = false; power = 1;
cell_obj_func = {...
%     FunctionFactory.getFunction(TypeFunction.Branin2, isMaximizeObj,power) ...
    FunctionFactory.getFunction(TypeFunction.Sum2, isMaximizeObj,power) ...
%     ,...
%     FunctionFactory.getFunction(TypeFunction.Thc2, isMaximizeObj,power) ...
%     , ...
%     FunctionFactory.getFunction(TypeFunction.Shc2, isMaximizeObj,power) ...
%     , ...
%     FunctionFactory.getFunction(TypeFunction.Levy6, isMaximizeObj,power)...
    };
% Specified settings. Remained settings are replaced by the defaults.

%% Make sure unconstrained.
cell_type_mean_func = {...
    {}...
};
cell_const_func = {...
    {}...
};

% cell_type_mean_func = {...
% %     {TypeFunction.Norm2, FuncModifier(@(x) 10*x, {@(x) x-8, @(x) x-15} )}...
% %     {TypeFunction.Gramacy1d2, FuncModifier(@(x) 5*x, {@(x) x, @(x) x} )}...
% %     {TypeFunction.Gramacy1d2, FuncModifier(@(x) x, {@(x) x, @(x) x} )}...
% %     {TypeFunction.SumSquare2, FuncModifier(@(x) 10*(x-50), {@(x) x-2.5, @(x) x-7.5} )}...
% % GOOD
% %     {TypeFunction.Gramacy1d2, FuncModifier(@(x) 10*x, {@(x) x, @(x) x} )}...
%     {TypeFunction.Gramacy1d2, FuncModifier(@(x) 3.*x, {@(x) x, @(x) x} )}...
% %     ,...
% %     {TypeFunction.Shc2}...
% %     ,...
% %     {TypeFunction.Shc2}...
% %     ,...
% %     {TypeFunction.Shc2}
%     };
% %     {TypeFunction.Norm6, FuncModifier(@(x) 50*x, {@(x) x-8, @(x) x-15} )}...


% cell_const_func = {...
%     %
%     MultipleConstraints(...
%         {Constraint(TypeConstraint.UnknownMeanConstraint, [], 0 ) }...
%     )...
% %     %
% %     , ...
% %     %
% %     MultipleConstraints(...
% %         {Constraint(TypeConstraint.UnknownMeanConstraint, [], 10 ) }...
% %     )    
% %     %
% %     , ...
% %     %
% %     MultipleConstraints(...
% %         {Constraint(TypeConstraint.UnknownMeanConstraint, [], 10 ) }...
% %     )    
% %     %
% %     , ...
% %     %
% %     MultipleConstraints(...
% %         {Constraint(TypeConstraint.UnknownMeanConstraint, [], 10 ) }...
% %     )    
%     %
% };
