function annotateText(fig,left, top, width, height, str,varargin)
%     left = 0.01;
%     top = 0.01;
%     width = 0.3;
%     height = 0.3;
    if(fig.isvalid)
        bottom = 1-top-height;
        pos = [left bottom width height];
        annotation(fig,'textbox',pos,'FontWeight','bold',...
            'LineStyle','none' ,...
            varargin{:},...
            'String',{...
    %     annotation(fig,'textbox',pos,'FontWeight','bold','LineWidth',2 ,'String',{...
            str...
            });
    %         'HorizontalAlignment','center',...
    %         'FontWeight','bold',...
    %         'FontName','Arial Black',...
    end
end