problem_name = ...
    'Gardner2';

% multiplier2Mean = 100;

isMaximizeObj = false; power = 1;
cell_obj_func = {...
    FunctionFactory.getFunction(TypeFunction.Gardener14_2Objd2, isMaximizeObj,power, FuncModifier(@(x) x+1, {@(x) x, @(x) x} )) ...
    };

cell_type_mean_func = {...
    {{TypeFunction.Gardener14_2C1d2, FuncModifier(@(x) (x+10)*80, {@(x) x, @(x) x} )}}...
    };
cell_const_func = {...
    MultipleConstraints(...
        {Constraint(TypeConstraint.UnknownMeanConstraint, [], 800 ) }...
    )...
};
sigmaObj = .1;
sigmaCons = .1;
