problem_name = ...
    'Gardner1';

% multiplier2Mean = 5;

isMaximizeObj = false; power = 1;
cell_obj_func = {...
    FunctionFactory.getFunction(TypeFunction.Gardener14_1Objd2,...
    isMaximizeObj,power, FuncModifier(@(x) x+2, {@(x) x, @(x) x} )) ...
    };

cell_type_mean_func = {...
    {{TypeFunction.Gardener14_1C1d2, FuncModifier(@(x) 10.*x, {@(x) x, @(x) x} )}}...
    };
cell_const_func = {...
    MultipleConstraints(...
        {Constraint(TypeConstraint.UnknownMeanConstraint, [], 0 ) }...
    )...
};
