classdef TypeInfillOptimizer
    enumeration
        GridUnconst, 
        DirectUnconst,
        GridConstSampling, 
        DirectConstSampling,
        GridConstWEI, 
        DirectConstWEI,
        DirectConstWEI_f_opt_within_xtest,
        DirectConstWEI_f_opt_within_xtest_using_mean,
        GridConstAdmm, 
        DirectConstAdmm,
        DirectConstAdmmNew,
        DirectConstNEI,
        DirectConstSobol,
        DirectConstPatternSearch,
        DirectConstE2CBO,
        DirectConstHWEI,
        DirectConstTesting2,
        DirectConstTesting3,
        DirectConstTesting4,
        DirectConstTesting5,
        DirectConstTesting6,
        DirectConstTesting7,
        DirectConstTesting8,
        DirectConstTesting9,
        DirectConstTesting
    end
end